# Generated by Django 4.1.3 on 2022-12-11 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0003_avancediario_fecha_alter_bebe_hora_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avancediario',
            name='tolerancia',
            field=models.CharField(blank=True, choices=[('Buena', 'Buena'), ('Mala', 'Mala'), ('Regular', 'Regular')], default='Regular', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='bebe',
            name='hora_nacimiento',
            field=models.TimeField(blank=True, default='23:03:06'),
        ),
    ]
