# Generated by Django 4.1.3 on 2022-12-13 01:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0005_alter_avancediario_bebe_alter_bebe_hora_nacimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avancediario',
            name='fecha',
            field=models.DateField(blank=True, default=datetime.date(2022, 12, 12)),
        ),
        migrations.AlterField(
            model_name='bebe',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, default=datetime.date(2022, 12, 12)),
        ),
        migrations.AlterField(
            model_name='bebe',
            name='hora_nacimiento',
            field=models.TimeField(blank=True, default='22:21:23'),
        ),
    ]
