# Generated by Django 4.1.3 on 2022-12-11 00:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bebe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=20)),
                ('nombre', models.CharField(blank=True, default='SIN NOMBRE', max_length=20)),
                ('apellido_paterno', models.CharField(blank=True, default='SIN APELLIDO', max_length=30)),
                ('apellido_materno', models.CharField(blank=True, default='SIN APELLIDO', max_length=30)),
                ('fecha_nacimiento', models.DateField(blank=True, default=datetime.date(2022, 12, 10))),
                ('hora_nacimiento', models.TimeField(blank=True, default='21:41:29')),
                ('peso', models.PositiveSmallIntegerField(blank=True, default=1)),
                ('talla', models.FloatField(blank=True, default=1.0)),
                ('madre', models.ForeignKey(blank=True, default='SIN MADRE', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_madre', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('padre', models.ForeignKey(blank=True, default='SIN PADRE', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_padre', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
