# Generated by Django 4.1.3 on 2022-12-11 01:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0002_alter_bebe_hora_nacimiento_avancediario'),
    ]

    operations = [
        migrations.AddField(
            model_name='avancediario',
            name='fecha',
            field=models.DateField(blank=True, default=datetime.date(2022, 12, 10)),
        ),
        migrations.AlterField(
            model_name='bebe',
            name='hora_nacimiento',
            field=models.TimeField(blank=True, default='22:34:03'),
        ),
    ]
