# Generated by Django 4.1.3 on 2022-12-11 02:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Hospital', '0004_alter_avancediario_tolerancia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avancediario',
            name='bebe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Hospital.bebe'),
        ),
        migrations.AlterField(
            model_name='bebe',
            name='hora_nacimiento',
            field=models.TimeField(blank=True, default='23:39:34'),
        ),
        migrations.AlterField(
            model_name='bebe',
            name='madre',
            field=models.ForeignKey(blank=True, default='SIN MADRE', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_madre', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AlterField(
            model_name='bebe',
            name='padre',
            field=models.ForeignKey(blank=True, default='SIN PADRE', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_padre', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
